version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.4-buster
    steps:
      - checkout
      - run: git submodule update --init
      - run: cd pysilfont && sudo python setup.py install && cd ..
      - run: sudo pip install fontmake
      - run: sudo apt-get install woff-tools
      - run: make linja-pona.woff
